package main

import (
	"encoding/json"
	"fmt"
)

type autogeneratedperson struct {
	First string `json:"First"`
	Last  string `json:"Last"`
	Age   int    `json:"Age"`
}

func main() {

	s := `[{"First":"james","Last":"bond","Age":35},{"First":"money","Last":"penny","Age":37}]` //`` not ''
	bs := []byte(s)
	fmt.Printf("%T\n", s)
	fmt.Printf("%T\n", bs) //[]uint8

	//people := []autogeneratedperson{}
	var people []autogeneratedperson

	 err := json.Unmarshal(bs, &people)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("\nall the data", people)

	for i, v := range people {
		fmt.Println("\nPerson number :", i)
		fmt.Println(v.First,v.Last, v.Age)
	}
}
